### ISSUE TITLE
Upgrade to v0.14.0

### ISSUE THREAD

**Issue by slateb** [rubysamurai/material_components_web-sass#4]
@rubysamurai MDC is now at v0.14.0. What is the task you're using to build the assets? Happy to put in a PR if that's outlined. Thanks.

**Comment by rubysamurai** [comment]
Sorry for late update, still trying to figure out #3. The gem is updated now.

As for assets build process, right now MDC changes internal structure pretty often between minor releases and every rake task I make usually gets broken and require manual re-check to confirm that everything is included properly. Once MDC enters stable stage it shouldn't be a problem.
