### ISSUE TITLE
box-shadows have quotes in their value

### ISSUE THREAD

**Issue by jankeesvw** [rubysamurai/material_components_web-sass#5]
I noticed that there were issues with box-shadows, the gem adds quotes to the box-shadow property ("0px 3px 1px -2px"). Which doesn't work.

![image](https://user-images.githubusercontent.com/167882/27636195-98a90500-5c0a-11e7-99d8-436e10253374.png)

On the left is the version with this Gem, on the right is the official one from https://material-components-web.appspot.com/button.html.

The NPM version doesn't suffer from this problem. Do you know what's going on?

**Comment by rubysamurai** [comment]
It seems related to an old `elevation`  component problem, that doesn't compile properly with Ruby Sass 3.3 and 3.4. 

Problem was reported by one of MDC core members to Sass team [here](https://github.com/sass/sass/issues/2241) and we apply the fix suggested in that issue, but apparently it doesn't work (compiles properly, but elevation is gone). 

I will apply alternate fix to this issue and release updated gem in a few minutes.

**Comment by jankeesvw** [comment]
Thanks @rubysamurai, I'll verify tomorrow if it works. I'll let you know!

**Comment by jankeesvw** [comment]
Issue is solved, thanks for your help @rubysamurai! ❤️
